import 'package:flutter_test/flutter_test.dart';

import '../../../tool/audit_pub_dependencies.dart';

void main() {
  group('parseHostedPackages', () {
    test('parses hosted pub packages from pubspec.lock', () {
      const lockfile = '''
# Generated by pub
packages:
  cloud_firestore:
    dependency: "direct main"
    description:
      name: cloud_firestore
      sha256: abc123
      url: "https://pub.dev"
    source: hosted
    version: "6.1.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  local_package:
    dependency: transitive
    description:
      path: ../local_package
      relative: true
    source: path
    version: "1.0.0"
sdks:
  dart: ">=3.9.0 <4.0.0"
''';

      final packages = parseHostedPackages(lockfile);

      expect(packages, hasLength(1));
      expect(packages.single.name, 'cloud_firestore');
      expect(packages.single.version, '6.1.0');
      expect(packages.single.dependencyType, 'direct main');
      expect(packages.single.source, 'hosted');
      expect(packages.single.registryUrl, 'https://pub.dev');
    });

    test('ignores hosted packages from non-pub registries', () {
      const lockfile = '''
packages:
  internal_package:
    dependency: transitive
    description:
      name: internal_package
      sha256: abc123
      url: "https://example.internal"
    source: hosted
    version: "1.2.3"
''';

      final packages = parseHostedPackages(lockfile);

      expect(packages, isEmpty);
    });
  });
}
