// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<FIREBASE_API_KEY>',
    appId: '1:864369516764:web:aad02dd9ef0aeec9f65419',
    messagingSenderId: '864369516764',
    projectId: 'nearpick-c0fea',
    authDomain: 'nearpick-c0fea.firebaseapp.com',
    storageBucket: 'nearpick-c0fea.firebasestorage.app',
    measurementId: 'G-HVVK9GP0MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '<FIREBASE_API_KEY>',
    appId: '1:864369516764:android:7064f34230e00fe6f65419',
    messagingSenderId: '864369516764',
    projectId: 'nearpick-c0fea',
    storageBucket: 'nearpick-c0fea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '<FIREBASE_API_KEY>',
    appId: '1:864369516764:ios:4caa7f870e3af0bef65419',
    messagingSenderId: '864369516764',
    projectId: 'nearpick-c0fea',
    storageBucket: 'nearpick-c0fea.firebasestorage.app',
    iosBundleId: 'com.example.nearpick',
  );
}
